rvm:
    - "2.0.0"
    - "1.9.3"
    - "1.8.7"
    - "jruby-1.7.4"
env:
    - OBJECTIFIED_SESSIONS_RAILS_TEST_VERSION=3.0.20
    - OBJECTIFIED_SESSIONS_RAILS_TEST_VERSION=3.1.12
    - OBJECTIFIED_SESSIONS_RAILS_TEST_VERSION=3.2.16
    - OBJECTIFIED_SESSIONS_RAILS_TEST_VERSION=4.0.2
    # - OBJECTIFIED_SESSIONS_RAILS_TEST_VERSION=master
matrix:
    exclude:
        -   rvm: 1.8.7
            env: OBJECTIFIED_SESSIONS_RAILS_TEST_VERSION=4.0.2
        -   rvm: 1.8.7
            env: OBJECTIFIED_SESSIONS_RAILS_TEST_VERSION=master
